import type { Metadata } from "next";
import Header from "./components/Header";
import "./globals.css";



export const metadata: Metadata = {
  title: "sesu blog",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className='m-7'>
        
        <Header/>
   
        {children}</body>
    </html>
  );
}
