import type { Metadata } from "next";

import "./globals.css";
import Header from "./components/Header";
import Banner from './components/Banner'



export const metadata: Metadata = {
  title: "sesu blog",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className='m-7'>
        <Header/>
        <Banner />
        {children}</body>
    </html>
  );
}
